version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_stock
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'stock_example'
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis_stock
    ports:
      - "6389:6379"

volumes:
  mysql-data: